server:
  port: 3000  # 한 칸 꼭 띄우기

spring:
  # 데이터 베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: PROJECT
    password: _aA123456

  # JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true  # 로그로 확인해볼 수 있음 (문제 파악 가능)
        format_sql: true  # sql 가독성을 높여줌
        use_sql_comments: true  # sql 코멘트 확인
    hibernate:
      ddlAuto: create


  # 라이브 리로드 활성
  devtools:
    livereload:
      enabled: true

  # 타임리프 설정
  thymeleaf:
    cache: false;
    prefix: file:src/main/resources/templates/  # 마지막에 /(슬래시) 꼭 붙이기!!

  # 정적 자원 설정(CSS, JS, 이미지)
  web:
    resources:
      staticLocations: file:src/main/resources/static/

  # 파일 업로드 설정 (최대 용량)
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 60MB

# 파일 경로 설정
file:
  url: /upload/
  path: c:/uploads/

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace